title: Anyone Can Code
patterns: ["**/*.md", "!**/node_modules", "!templates/**", "!frontend/**"]
base: /anyonecancode/instructions/
themeConfig:
  repo: "microsoft/anyonecancode"
  editLinks: true
  sidebar:
    [
      ["./", "Home"],
      "./instructions/day1/Github/",
      "./instructions/day1/Application/",
      "./instructions/day2/Speech/",
    ]
plugins: [["vuepress-plugin-code-copy", true]]
