name: pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '12'

      - run: |
          npm ci
          npm run build
        working-directory: day1/Application/female-app-innovation-frontend
      - name: Upload result of Application build
        uses: actions/upload-artifact@v2
        with:
          name: static-website
          path: day1/Application/female-app-innovation-frontend
  deploy:
    runs-on: ubuntu-latest
    needs: build

    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Download build of static website
        uses: actions/download-artifact@v2
        with:
          name: static-website
          path: day1/Application/female-app-innovation-frontend
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: day1/Application/female-app-innovation-frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
