name: pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "16"

      - run: |
          npm ci
          npm run build -- --base=$BASE_URL
        env:
          BASE_URL: anyonecancode
          VITE_FACE_API_KEY: ${{ secrets.VITE_FACE_API_KEY }}
          VITE_SPEECH_API_KEY: ${{ secrets.VITE_SPEECH_API_KEY }}
          VITE_IMAGE_API_URL: ${{secrets.VITE_IMAGE_API_URL}}
          VITE_FACE_API_ENDPOINT: ${{secrets.VITE_FACE_API_ENDPOINT}}

        working-directory: frontend
      - name: Upload result of Application build
        uses: actions/upload-artifact@v2
        with:
          name: static-webapp
          path: frontend/dist

  build-website:
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'microsoft' }}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: "14"
      - run: npm init -y
      - run: npm install vuepress vuepress-plugin-code-copy
      - run: node_modules/.bin/vuepress build
      - name: Upload result of vuepress build
        uses: actions/upload-artifact@v2
        with:
          name: static-website
          path: .vuepress/dist
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-app
      - build-website
    environment:
      name: pages
      url: https://${{ github.repository_owner }}.github.io/anyonecancode

    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Download build of static app
        uses: actions/download-artifact@v2
        with:
          name: static-webapp
          path: dist
      - name: Download build of static website
        uses: actions/download-artifact@v2
        if: ${{ github.repository_owner == 'microsoft' }}}
        with:
          name: static-website
          path: dist/instructions
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
